# Copyright 2023 OpenStack Foundation.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""add resource inventory

Revision ID: e20cbce0504c
Revises: 02e2f2186d98
Create Date: 2023-07-06 14:45:39.036229

"""

# revision identifiers, used by Alembic.
revision = 'e20cbce0504c'
down_revision = '02e2f2186d98'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instance_reservations', sa.Column('resource_inventory', sa.Text().with_variant(mysql.MEDIUMTEXT(), 'mysql'), nullable=True))
    op.add_column('instance_reservations', sa.Column('resource_traits', sa.Text().with_variant(mysql.MEDIUMTEXT(), 'mysql'), nullable=True))
    op.add_column('instance_reservations', sa.Column('source_flavor', sa.Text().with_variant(mysql.MEDIUMTEXT(), 'mysql'), nullable=True))
    op.alter_column('instance_reservations', 'affinity',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('instance_reservations', 'affinity',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.drop_column('instance_reservations', 'source_flavor_id')
    op.drop_column('instance_reservations', 'resource_traits')
    op.drop_column('instance_reservations', 'resource_inventory')
    # ### end Alembic commands ###